// 200 AI Tells — Data
// Each item: [severity, name, description, previewType, previewConfig]
// severity: 0=instant, 1=common, 2=subtle
// previewType maps to a generator in previews.js

const DATA = [
  { cat: "Color & Gradient", items: [
    [0,"Purple/indigo default accent","<code>bg-indigo-500</code>, <code>bg-violet-600</code>, <code>bg-purple-700</code> dominating","grad","linear-gradient(135deg,#6366f1,#7c3aed,#7e22ce)"],
    [0,"Purple-to-blue hero gradient","<code>bg-gradient-to-r from-purple-500 to-blue-500</code>","grad","linear-gradient(90deg,#a855f7,#3b82f6)"],
    [1,"Purple-to-pink gradient variant","<code>from-purple-500 to-pink-500</code> on buttons","grad","linear-gradient(90deg,#a855f7,#ec4899)"],
    [1,"Cyan-to-indigo gradient","<code>from-cyan-400 to-indigo-600</code>","grad","linear-gradient(90deg,#22d3ee,#4f46e5)"],
    [0,"Gradient text on H1","<code>bg-clip-text text-transparent</code> on headlines","gtext","The Future"],
    [1,"Sterile white backgrounds","<code>bg-white</code> or <code>bg-gray-50</code> clinical feel","solid","#f9fafb"],
    [1,"Flat dark mode","<code>bg-gray-900</code> zero surface nuance","solid","#111827"],
    [1,"Neon accents in dark mode","Cyan, pink, acid green on dark","neon",""],
    [2,"#6366f1 everywhere","Indigo-500 as the go-to accent","swatch","#6366f1"],
    [1,"Tailwind Blue","<code>text-blue-600</code> / <code>bg-blue-500</code> fallback","swatch","#3b82f6"],
    [2,"Unmodified Tailwind palette","<code>indigo-500</code>, <code>gray-100</code> no customization","palette","default"],
    [2,"Timid color distribution","Evenly-distributed, no dominant color","palette","timid"],
    [1,"Radial gradient card fills","Random radial gradients inside cards","grad","radial-gradient(circle at 30% 40%,#a855f7 0%,#6366f1 50%,#3b82f6 100%)"],
    [1,"Aurora/light-leak backgrounds","Blurred colorful shapes behind content","aurora",""],
    [1,"CSS mesh gradient heroes","Layered <code>linear-gradient</code> backgrounds","mesh",""],
    [2,"Same-color fill + border","Low-opacity fill with matching border","fillbdr","#6366f1"],
    [1,"Soft pastel voids","Glassmorphic cards in pastel color fields","pastel",""],
    [2,"No semantic color system","Colors decorative rather than functional","nosem",""],
    [1,"Semi-transparent purple overlay","Gradient overlay on hero images","overlay",""],
    [1,"Neon purple on dark","Neon purple accent as universal dark theme","grad","linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)"],
    [2,"Binary theming","<code>bg-white dark:bg-gray-900</code> only","binary",""],
    [2,"Uniform 0.1 opacity shadows","<code>rgba(0,0,0,0.1)</code> on every card","shadow",""]
  ]},
  { cat: "Typography", items: [
    [0,"Inter font","The Comic Sans of AI","font","Inter"],
    [1,"Roboto fallback","Secondary default font","font","Roboto"],
    [1,"System sans-serif","<code>font-sans</code> resolving to Arial","font","Arial"],
    [1,"Space Grotesk convergence","AI converges here avoiding Inter","font","Space Grotesk"],
    [2,"Open Sans safe choice","Safe alternative from training data","font","Open Sans"],
    [0,"No font pairing","Single font family for everything","fontpair","single"],
    [1,"font-semibold everywhere","Headings use semibold only","weight","600"],
    [1,"Conservative size jumps","1.5x between headings instead of 3x+","scale","conservative"],
    [2,"Identical type scale","<code>text-2xl</code>, <code>text-lg</code>, <code>text-sm</code> everywhere","scale","identical"],
    [1,"Generic uppercase headers","<code>uppercase tracking-wide</code>","upper","SECTION TITLE"],
    [2,"Missing font import","Declaration without the actual import","code","font-family: 'Poppins'"],
    [0,"No display font","Same font for headings and body","fontpair","nodisplay"],
    [2,"Binary weight usage","Only <code>font-bold</code> and <code>font-medium</code>","weight","binary"],
    [2,"tracking-tighter as flourish","Only typographic treatment on hero","code","tracking-tighter"],
    [2,"Default Tailwind type scale","Zero customization of built-in scale","scale","default"],
    [2,"No custom typefaces","Real brands use custom type, AI never does","font","Inter"]
  ]},
  { cat: "Layout & Structure", items: [
    [0,"Hero Left Text, Right Image","Most common AI landing page pattern","layout","hero-lr"],
    [0,"Three feature boxes below hero","<code>grid-cols-3</code> icon + title + desc cards","layout","3col"],
    [0,"Template section ordering","Hero → Features → Testimonials → Pricing → CTA → Footer","layout","sections"],
    [1,"Centered hero + gradient CTA","Centered text with gradient button","layout","center-cta"],
    [1,"Perfect symmetry everywhere","No asymmetry or grid-breaking elements","layout","symmetry"],
    [1,"Sidebar dashboard","<code>flex h-screen</code> with <code>w-64 border-r</code>","layout","sidebar"],
    [2,"max-w-7xl mx-auto on everything","Same container on every section","code","max-w-7xl mx-auto"],
    [1,"Stacked cards","Cards stacked with no spatial composition","layout","stacked"],
    [2,"Uniform padding","<code>p-4</code> cards, <code>p-6</code> sections everywhere","code","p-4 / p-6"],
    [2,"Uniform spacing","<code>space-y-4</code> / <code>space-y-6</code> everywhere","code","space-y-4"],
    [1,"Logo strip below hero","Grayscale partner logos in a row","layout","logos"],
    [1,"Narrative-less carousel","Carousel as filler with no purpose","layout","carousel"],
    [1,"Cards inside cards","3+ levels of nested containers","layout","nested"],
    [1,"Hero Metric Layout","Big number + small label + gradient accent","layout","metric"],
    [2,"Identical measurements","24px padding, 16px radius everywhere","code","24px / 16px"],
    [1,"Default bento grid","Bento grid for features as trendy default","layout","bento"],
    [1,"Oversized hero sections","Hero taking disproportionate viewport","layout","hero-big"],
    [1,"Gradient + floating cards","Full-bleed gradient + white cards on top","layout","float-cards"],
    [2,"Nested box decoration","Icons inside boxes inside other boxes","layout","nested-box"],
    [1,"Three-tier pricing","Exactly 3 tiers every time","layout","pricing"],
    [1,"Dashboard-as-hero","Complex UI screenshot nobody understands","layout","dash-hero"],
    [1,"Universal responsive grid","<code>grid-cols-1 md:2 lg:3 gap-6</code>","code","grid-cols-1 md:2 lg:3"],
    [2,"flex-col md:flex-row","Every responsive conversion","code","flex-col md:flex-row"],
    [1,"Broken mobile layouts","Desktop-only designs that break on mobile","layout","broken-mobile"],
    [2,"Centering everything","<code>flex items-center justify-center</code>","code","items-center justify-center"],
    [2,"Emotionally cold layouts","Perfectly symmetrical, zero tension","layout","cold"],
    [2,"Repetitive mood sections","Sections restating same value differently","layout","repeat"]
  ]},
  { cat: "CSS & Tailwind", items: [
    [1,"rounded-2xl on everything","Excessive border-radius on all elements","css","border-radius: 16px"],
    [1,"Pill buttons","<code>rounded-full</code> on every CTA","btn","pill"],
    [1,"Universal shadow","<code>shadow-lg</code> / <code>shadow-xl</code> no variation","css","box-shadow: 0 10px 15px rgba(0,0,0,.1)"],
    [1,"Default glassmorphism","<code>backdrop-blur-lg bg-white/30</code>","glass",""],
    [2,"border border-gray-200","On every card without exception","css","border: 1px solid #e5e7eb"],
    [0,"The AI gradient","<code>from-purple-500 to-blue-500</code>","grad","linear-gradient(90deg,#a855f7,#3b82f6)"],
    [1,"Generic transition","<code>transition-all duration-300</code>","code","transition-all duration-300"],
    [2,"hover:shadow-lg only","Only hover effect on cards","css","hover: shadow-lg"],
    [2,"text-gray-600 body text","All body text without variation","css","color: #4b5563"],
    [2,"Uniform container padding","<code>p-6</code> / <code>p-8</code> on every container","code","p-6 / p-8"],
    [2,"Uniform grid gaps","<code>gap-4</code> / <code>gap-6</code> everywhere","code","gap-4 / gap-6"],
    [2,"One-shade-darker hover","<code>hover:bg-blue-700</code> only","btn","darker"],
    [2,"bg-white dark:bg-gray-800","Every card background","css","bg: white → #1f2937"],
    [2,"text-gray-600 dark:text-gray-400","All secondary text","css","color: #4b5563 → #9ca3af"],
    [2,"Mixed border-radius","Inconsistent rounded values on one page","css","mixed radii"],
    [2,"w-full everywhere","Applied to every input and button","code","w-full"],
    [2,"Unnecessary overflow-hidden","On containers when nothing overflows","code","overflow-hidden"],
    [2,"text-sm text-gray-500","Every helper text and caption","css","font: 14px #6b7280"],
    [2,"Mixed styling approaches","Inline + CSS modules + Tailwind together","code","style={{}} + className"],
    [2,"Glowing button hover","<code>shadow-indigo-500/50</code> glow","btn","glow"],
    [1,"min-h-screen bg-gray-50","Universal page background","solid","#f9fafb"],
    [2,"Identical button padding","<code>px-6 py-3</code> on every button","code","px-6 py-3"]
  ]},
  { cat: "Components", items: [
    [0,"shadcn/ui defaults","<code>Button</code>, <code>Card</code>, <code>Dialog</code> zero customization","comp","shadcn"],
    [0,"Lucide React icons","<code>Zap, Heart, Star</code> in every section","comp","lucide"],
    [1,"Dark mode toggle top-right","In the corner of every AI app","comp","toggle"],
    [1,"Generic icon feature cards","Lucide icon + title + paragraph","comp","feat-card"],
    [1,"Most Popular badge","On middle pricing tier every time","comp","badge"],
    [1,"Forms without validation","No error states or feedback","comp","form"],
    [2,"Toast for everything","<code>sonner</code> for every user action","comp","toast"],
    [2,"hover:shadow-lg interaction","Only interactive card feedback","css","hover: shadow-lg"],
    [1,"Template navbar","Logo left, links center, CTA right","comp","navbar"],
    [2,"Unnecessary cookie banner","Generated even when not needed","comp","cookie"],
    [1,"Star ratings in testimonials","Filled/unfilled stars","comp","stars"],
    [1,"New/Beta pill badges","<code>rounded-full bg-purple-100 text-xs</code>","comp","pill-badge"],
    [2,"Heroicons as alternative","When not Lucide, always Heroicons","comp","heroicons"],
    [2,"Framer Motion default","Default animation library","code","framer-motion"],
    [2,"CVA auto-installed","<code>class-variance-authority</code> with shadcn","code","cva"],
    [2,"@/components/ui/ structure","shadcn default file structure","code","components/ui/"],
    [2,"cn() utility","From <code>@/lib/utils</code>","code","cn()"],
    [2,"React Hook Form + Zod","Default form validation combo","code","useForm + z.object"],
    [2,"Radix UI underneath","Radix primitives underneath everything","code","@radix-ui/react-*"]
  ]},
  { cat: "Animation & Motion", items: [
    [0,"Subtle fades only","<code>transition-all duration-300</code> generic, no real motion","anim","fade"],
    [1,"hover:scale-105 on cards","Uniform scale on every card","anim","scale"],
    [1,"Staggered fade-in","Incrementing delays on card grids","anim","stagger"],
    [1,"Entrance-only animations","No scroll, micro-interaction, or exit anim","anim","entrance"],
    [2,"Universal timing","Same <code>duration-300 ease-in-out</code>","code","duration-300 ease-in-out"],
    [1,"Hover lift + shadow","<code>hover:shadow-lg hover:-translate-y-1</code>","anim","lift"],
    [2,"animate-pulse without logic","Placeholder pulse no loading state","anim","pulse"],
    [2,"animate-ping notifications","For notification indicators only","anim","ping"],
    [2,"animate-bounce loading","For loading indicators","anim","bounce"],
    [1,"No loading states","Forms submit with no indicator","comp","no-load"],
    [1,"Generic scroll fade","Same fade-in on every element","anim","scroll-fade"],
    [2,"Snapping buttons","Buttons snap instead of easing","anim","snap"],
    [1,"Missing skeleton screens","No loading skeleton states","comp","skeleton"],
    [1,"No brand motion","All motion generic, no personality","anim","generic"],
    [0,"Static by default","Zero animations unless requested","anim","static"]
  ]},
  { cat: "Content & Copy", items: [
    [0,"Template variables shipped","<code>{{COMPANY_NAME}}</code> left in production","text","{{COMPANY_NAME}}"],
    [0,"Transform your business","Innovative solutions / Revolutionize the way","text","Transform Your Business Today"],
    [0,"Generic CTAs","Get Started / Let's Go / Start Now","btn","generic-cta"],
    [0,"Fake testimonials","Sarah M., CEO at [Company]","text","— Sarah M., CEO"],
    [1,"AI buzzwords","Cutting-edge, Leverage, Streamline, Seamless","text","Leverage cutting-edge solutions"],
    [1,"In today's fast-paced...","Opening paragraph pattern","text","In today's fast-paced digital landscape..."],
    [1,"Rule of Three","Fast, reliable, and secure","text","Fast. Reliable. Secure."],
    [1,"Lorem ipsum placeholders","Placeholder text saying nothing","text","Lorem ipsum dolor sit amet..."],
    [2,"Em dash overuse","Excessive em dashes throughout","text","We believe — truly — in..."],
    [1,"Negation structure","It's not about X, it's about Y","text","It's not about code — it's about vision"],
    [2,"Generic meta descriptions","Template-generated descriptions","code","meta name=description"],
    [2,"Broken OpenGraph","Missing OG metadata","code","og:title missing"],
    [2,"Outdated copyright","2024 when current year is 2026","text","© 2024 Company Inc."],
    [1,"Generic About Us","Could apply to any company","text","We're passionate about innovation"],
    [1,"Impossible metrics","99.9% uptime, 10x faster","text","99.9% Uptime | 10x Faster"],
    [1,"Emoji headers","Rocket, sparkle, gem as decorators","text","Features"],
    [1,"Your all-in-one platform","Generic value proposition","text","Your all-in-one platform for..."],
    [1,"Empty scalability claims","Scale without limits / Empower","text","Scale Without Limits"],
    [2,"Hedging language","May help you, can potentially","text","...may help you potentially..."],
    [1,"Generic superlatives","Best-in-class / world-class","text","Best-in-Class Solution"],
    [0,"Dead giveaway vocabulary","Delve / tapestry / landscape","text","Delve into the tapestry of..."],
    [1,"Vague aspirational headlines","Build the future of work","text","Build the Future of Work"],
    [1,"Buzzword features","Leverage AI to unlock insights","text","Leverage AI to Unlock Insights"],
    [2,"Repetitive value propositions","Same point in different words","text","repeated copy"]
  ]},
  { cat: "Code & Technical", items: [
    [0,"Universal default stack","Next.js + TypeScript + Tailwind + shadcn","code","next + ts + tw + shadcn"],
    [1,"Vercel subdomain","<code>yourapp.vercel.app</code>","code","*.vercel.app"],
    [1,"Supabase default backend","Supabase for backend/auth","code","@supabase/supabase-js"],
    [1,"use client everywhere","At top of every component","code","'use client'"],
    [1,"Obvious comments","<code>// TODO: implement</code>","code","// TODO: implement"],
    [1,"useState + useEffect spaghetti","React state for everything","code","useState + useEffect"],
    [2,"Backup files left behind","<code>index-backup-2.html</code> in repo","code","*-backup-*.html"],
    [1,"Duplicate components","Same structure repeated","code","Button.tsx × 3"],
    [1,"Missing accessibility","No ARIA labels or alt text","code","aria-label missing"],
    [0,"Hardcoded API keys","Secrets in frontend code","code","sk_live_xxx..."],
    [1,"Bad SEO hierarchy","Incorrect H1-H6 structure","code","h1 > h3 > h2"],
    [1,"Console errors on load","Untested code throwing errors","code","Uncaught TypeError"],
    [2,"Reimplementing utilities","Recreating existing functions","code","function formatDate()..."],
    [2,"Scattered auth logic","Auth in 3+ locations","code","auth scattered"],
    [2,"Competing state management","2+ patterns fighting","code","useState + Redux + Zustand"],
    [2,"Hardcoded assumptions","Assumptions future features violate","code","if (user.role === 'admin')"],
    [2,"N+1 queries","Quadratic loops nobody measured","code","users.map(u => getOrders(u))"],
    [2,"Switch statement overuse","Complex switches in components","code","switch(type) { case..."],
    [2,"Over-commenting","Excessive obvious comments","code","// increment counter\\ni++"],
    [1,"Broken nav links","Links leading to 404","code","/docs → 404"],
    [2,"Unminified production","Code not bundled or tree-shaken","code","bundle: 2.4MB"],
    [2,"Descriptive class names","Generic rather than semantic CSS","code",".blue-button-large"],
    [2,"Convention mismatch","Classes in functional codebase","code","class + hooks"],
    [1,"v0 artifact strings","Detectable in JS bundles","code","v0.dev/artifacts"],
    [1,"Lovable/Bolt identifiers","Platform fingerprints in source","code","lovable-tagger.js"]
  ]},
  { cat: "Imagery & Visual", items: [
    [0,"3D humans with glowing orbs","Abstract figures in impossible poses","img","orb"],
    [1,"Floating abstract dashboards","Dashboards floating in space","img","float-dash"],
    [1,"Flat SaaS characters","Round heads, pastel limbs","img","saas-char"],
    [1,"Rocket launch people","Vectors high-fiving or launching rockets","img","rocket"],
    [1,"3D blobs with charts","Random orbs with charts","img","blob"],
    [1,"Faceless productivity scenes","Stock laptop/office imagery","img","stock"],
    [2,"Uncanny symmetry","Slightly-too-smooth AI illustrations","img","uncanny"],
    [1,"Unsplash placeholders","Stock photos left as placeholders","img","unsplash"],
    [1,"Generic mockup frames","Hero with empty device mockups","img","mockup"],
    [1,"Sparkle decoration","Used as badge/header decorators","img","sparkle"]
  ]},
  { cat: "Meta & Structural", items: [
    [1,"No design tokens","Raw utilities instead of CSS variables","code","no var(--*)"],
    [1,"No custom color ramps","Relying on Tailwind built-in colors","palette","tw-only"],
    [0,"Logo-swap test fail","Swap logo — site is indistinguishable","img","logo-swap"],
    [2,"White space hiding emptiness","Spacing hiding lack of content","layout","whitespace"],
    [1,"Binary light/dark mode","Only two themes, no brand palette","binary",""],
    [1,"The Linear clone","Dark + motion + blue-indigo hero","grad","linear-gradient(135deg,#0f172a,#1e293b,#334155)"],
    [0,"No brand voice","Design could apply to any company","text","[Any Company] — Innovate Today"],
    [0,"Sea of Sameness","Recognizable as AI within 0.5s","img","sameness"],
    [1,"Uncanny production-readiness","Polished but seen 1,000 times","img","uncanny-prod"],
    [2,"Excessive optimism","Great job! everywhere","text","Great job! You're doing amazing!"],
    [1,"Hosting fingerprints","Default Vercel/Netlify subdomains","code","*.vercel.app"],
    [1,"Missing favicon","No favicon or generic default","comp","no-favicon"],
    [1,"Disconnected forms","Forms not connected to anything","comp","dead-form"],
    [2,"Missing Schema.org","No structured data markup","code","ld+json missing"],
    [1,"No design system","Using raw library defaults","code","no design system"],
    [2,"Missing viewport meta","No viewport meta tags","code","meta viewport missing"],
    [2,"Identical header/footer","Same structure all pages","layout","same-hf"],
    [2,"Zero custom Tailwind layers","Only base + components + utilities","code","@tailwind × 3"],
    [2,"Missing prefers-reduced-motion","No accessibility animation controls","code","prefers-reduced-motion"],
    [2,"Cookie-cutter meta tags","Template descriptions all identical","code","meta × template"]
  ]}
];
